(use-package meow
  :ensure t
  :demand t
  :config
  ;; emacs keybind to access local leader map
  (setq emacs-local-leader-prefix "C-?")
  ;; meow keybind alias for local leader map
  (setq meow-local-leader-prefix "/")
  (setq meow-local-leader-insert-prefix "C-/")
  ;; keep the expand hints around a while longer
  (setq meow-expand-hint-remove-delay 3.0)
  ;; start git commits in insert mode
  (add-hook 'git-commit-mode-hook 'meow-insert-mode)
  (meow-global-mode 1))

(setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

(setq global-leader-map
      (let ((keymap (make-sparse-keymap)))
        (define-key keymap (kbd "c") 'meow-keypad-start)
        (define-key keymap (kbd "g") 'meow-keypad-start)
        (define-key keymap (kbd "h") 'meow-keypad-start)
        (define-key keymap (kbd "m") 'meow-keypad-start)
        (define-key keymap (kbd "x") 'meow-keypad-start)
        keymap))

(setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)

(meow-motion-define-key
  '("j" . meow-next)
  '("k" . meow-prev)
  '("<escape>" . ignore))

(meow-leader-define-key
  ;; Use SPC (0-9) for digit arguments.
  '("1" . meow-digit-argument)
  '("2" . meow-digit-argument)
  '("3" . meow-digit-argument)
  '("4" . meow-digit-argument)
  '("5" . meow-digit-argument)
  '("6" . meow-digit-argument)
  '("7" . meow-digit-argument)
  '("8" . meow-digit-argument)
  '("9" . meow-digit-argument)
  '("0" . meow-digit-argument)
  '("/" . meow-keypad-describe-key)
  '("?" . meow-cheatsheet))

(meow-normal-define-key
  '("0" . meow-expand-0)
  '("9" . meow-expand-9)
  '("8" . meow-expand-8)
  '("7" . meow-expand-7)
  '("6" . meow-expand-6)
  '("5" . meow-expand-5)
  '("4" . meow-expand-4)
  '("3" . meow-expand-3)
  '("2" . meow-expand-2)
  '("1" . meow-expand-1)
  '("-" . negative-argument)
  '(";" . meow-reverse)
  '("," . meow-inner-of-thing)
  '("." . meow-bounds-of-thing)
  '("[" . meow-beginning-of-thing)
  '("]" . meow-end-of-thing)
  '("a" . meow-append)
  '("A" . meow-open-below)
  '("b" . meow-back-word)
  '("B" . meow-back-symbol)
  '("c" . meow-change)
  '("d" . meow-delete)
  '("D" . meow-backward-delete)
  '("e" . meow-next-word)
  '("E" . meow-next-symbol)
  '("f" . meow-find)
  '("g" . meow-cancel-selection)
  '("G" . meow-grab)
  '("h" . meow-left)
  '("H" . meow-left-expand)
  '("i" . meow-insert)
  '("I" . meow-open-above)
  '("j" . meow-next)
  '("J" . meow-next-expand)
  '("k" . meow-prev)
  '("K" . meow-prev-expand)
  '("l" . meow-right)
  '("L" . meow-right-expand)
  '("m" . meow-join)
  '("n" . meow-search)
  '("o" . meow-block)
  '("O" . meow-to-block)
  '("p" . meow-yank)
  '("q" . meow-quit)
  '("Q" . meow-goto-line)
  '("r" . meow-replace)
  '("R" . meow-swap-grab)
  '("s" . meow-kill)
  '("t" . meow-till)
  '("u" . meow-undo)
  '("U" . meow-undo-in-selection)
  '("v" . meow-visit)
  '("w" . meow-mark-word)
  '("W" . meow-mark-symbol)
  '("x" . meow-line)
  '("X" . meow-goto-line)
  '("y" . meow-save)
  '("Y" . meow-sync-grab)
  '("z" . meow-pop-selection)
  '("'" . repeat)
  '("<escape>" . ignore))

